name: Windows Build
on:
  push:
    paths:
      - 'windows/**.cpp'
      - 'windows/**.h'
      - '**.sln'
      - '.github/**.yml'
      - 'scripts/**.ps1'
env:
  VS_PROGRAM: 1
  VS_FILE: 0
  VS_EPOCH:
  VS_FULL:
  RELEASE_TITLE: "RGB Diff"
  RELEASE_FILE: "./docs/md/pre-release.md"
  BIN_DEFAULT: "rgbdiff"
  PRERELEASE: True
  GH_TOKEN: ${{ github.token }}
jobs:
  windows_build:
    runs-on: windows-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
      - name: MSBuild Setup
        uses: microsoft/setup-msbuild@v2
      - name: Windows Build
        shell: pwsh
        id: windows_build_id
        run: |
          if (Test-Path -Path .\scripts\functions.ps1){
            . .\scripts\functions.ps1
            $br = BreakLine -Width 100 -Lines 2
          }
          $br; 'Building application.'; $br
          try {
            .\scripts\buildwindows.ps1
          } catch {
            $br; $_.Exception.Message; $br
          }
          $br; 'Retrieving MD5 hash.'
          $epoch = [decimal] [datetimeoffset]::UtcNow.ToUnixTimeMilliseconds()
          "VS_FULL=${{ env.VS_PROGRAM }}.${{ env.VS_FILE }}.$epoch" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          "${{ env.VS_PROGRAM }}.${{ env.VS_FILE }}.$epoch" | Out-File -FilePath .\docs\latest_tag_name.txt
          $rgbdiff_x64_md5_text = @'
          {
            "schemaVersion": 1,
            "color": "2E9778",
            "label": "rgbdiff-x64.exe MD5",
            "message": "PLACEHOLDER",
            "labelColor": "1d1d1d",
            "style": "for-the-badge",
            "namedLogo": "windows"
          }
          '@
          $br; 'Writing MD5 hash to .\docs\json\rgbdiff_x64_md5.json.'
          Write-Output "$rgbdiff_x64_md5_text" > .\docs\json\rgbdiff_x64_md5.json
          $file = '.\docs\json\rgbdiff_x64_md5.json'
          $md5 = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
          $hash = $(Get-FileHash -Path "build\windows\rgbdiff.exe" -Algorithm MD5).Hash
          ((Get-Content -path $file -Raw) -replace 'PLACEHOLDER',$hash) | Set-Content -Path "$file"
          $br; 'Pushing newly generated config files to the repository.'
          git add .\docs\json\* .\docs\latest_tag_name.txt
          git config --global user.name 'Lateralus138'
          git config --global user.email 'Lateralus138@users.noreply.github.com'
          git commit --allow-empty -am "Pushed .\docs\json\* to master. - $(Get-Date ([datetime]::UtcNow)) UTC"
          git push --force origin master
          $br; 'Windows build Complete.'; $br
      - name: Release Windows
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          tag: ${{ env.VS_FULL }}
          name: ${{ env.RELEASE_TITLE }} - v${{ env.VS_FULL }}
          bodyFile: ${{ env.RELEASE_FILE }}
          prerelease: ${{ env.PRERELEASE }}
          artifacts: build\windows\${{ env.BIN_DEFAULT }}.exe
          token: ${{ secrets.GITHUB_TOKEN }}      
  build_linux:
    name: Build Linux Project
    runs-on: ubuntu-latest
    needs: [windows_build]
    steps:
    - name: Checkout Linux
      uses: actions/checkout@v3
    - name: Build Linux
      id: make_linux_rgbdiff
      run: |
        git config --global user.name 'Lateralus138' || exit 255
        git config --global user.email 'Lateralus138@users.noreply.github.com' || exit 254
        git fetch || exit 253
        git checkout FETCH_HEAD -- docs/latest_tag_name.txt || exit 252
        echo "VS_FULL=$(cat docs/latest_tag_name.txt)" >> $GITHUB_ENV
        version="$(cat docs/latest_tag_name.txt)"
        version="$(echo $version | tr -d '\r')"
        cd ./linux || exit 251
        chmod u+x prebuild || exit 250
        make || exit 249
        if [[ -f "release/dynamic/rgbdiff" ]]; then
          MESSAGEL="{\n\t\"schemaVersion\": 1,\n\t\"color\": \"2E9778\",\n\t\"label\": \"rgbdiff MD5\",\n\t\"message\": \"PLACEHOLDER\",\n\t\"labelColor\": \"1d1d1d\",\n\t\"style\": \"for-the-badge\",\n\t\"namedLogo\": \"linux\"\n}"
          MD5L=($(md5sum release/dynamic/rgbdiff))
          MESSAGEL="${MESSAGEL//PLACEHOLDER/${MD5L}}"
          cd ../ || exit 247
          echo -e "$MESSAGEL" > ./docs/json/rgbdiff_linux_md5.json || exit 246
          git add ./docs/json/rgbdiff_linux_md5.json || exit 245
          git commit --allow-empty -am "Pushed ./docs/json/rgbdiff_linux_md5.json to master. - $(date -u)" || exit 244
          git push --force origin master || exit 243
          gh release upload "$version" linux/release/dynamic/rgbdiff || exit 242
        else
          exit 248
        fi
        cd linux || exit 241
        chmod 0755 release/dynamic/rgbdiff || exit 240
        mkdir debian/usr/bin || exit 239
        cp release/dynamic/rgbdiff debian/usr/bin || exit 238
        dpkg-deb --root-owner-group --build debian rgbdiff-1.0.0.deb || exit 237
        MESSAGED="{\n\t\"schemaVersion\": 1,\n\t\"color\": \"2E9778\",\n\t\"label\": \"rgbdiff-1.0.0.deb MD5\",\n\t\"message\": \"PLACEHOLDER\",\n\t\"labelColor\": \"1d1d1d\",\n\t\"style\": \"for-the-badge\",\n\t\"namedLogo\": \"debian\"\n}"
        MD5D=($(md5sum rgbdiff-1.0.0.deb))
        MESSAGED="${MESSAGED//PLACEHOLDER/${MD5D}}"
        cd ../../ || exit 236
        echo -e "$MESSAGED" > ./docs/json/rgbdiff_debian_md5.json || exit 235
        git add ./docs/json/rgbdiff_debian_md5.json || exit 234
        git commit --allow-empty -am "Pushed ./docs/json/rgbdiff_debian_md5.json to master. - $(date -u)" || exit 233
        git push --force origin master || exit 232
        gh release upload "$version" linux/rgbdiff-1.0.0.deb || exit 231