name: test flow

on:
  workflow_run:
    workflows: [Working Windows Workflow]
    types: [completed]
    branches: [working]

jobs:
  test_w:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: test_1
        shell: pwsh
        run: |
          "Success"
  test_l:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: test_2
        shell: pwsh
        run: |
          "Failure"