name: test

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Working Windows Workflow']
    types: [completed]

jobs:
  test:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'Failure' }}
    steps:
      - name: test_1
        shell: pwsh
        run: |
          "Success"