name: test

on:
  workflow_dispatch:
  workflow_run:
    branches:
      - 'working'
    workflows: ['Working Windows Workflow']
    types: [completed]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: test_1
        shell: pwsh
        run: |
          "Success"