name: test

on:
  workflow_run:
    workflows:
      - 'Working Windows Workflow'
    types:
      - 'completed'
    branches:
      - 'working'

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: test_1
        shell: pwsh
        run: |
          "Success"