name: Windows Build
on:
  push:
    paths:
      - 'windows/**.cpp'
      - 'windows/**.h'
      - '**.sln'
      - '.github/**.yml'
      - 'scripts/**.ps1'

jobs:
  windows_build:
    runs-on: windows-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
      - name: MSBuild Setup
        uses: microsoft/setup-msbuild@v2
      - name: Windows Build
        shell: pwsh
        id: windows_build_id
        run: |
          if (Test-Path -Path .\scripts\functions.ps1){
            . .\scripts\functions.ps1
            $br = BreakLine -Width 100 -Lines 2
          }
          $br
          try {
            .\scripts\buildwindows.ps1
          } catch {
            $_.Exception.Message
            $br
          }
          $br
