name: Windows Build
on:
  push:
    paths:
      - 'windows/**.cpp'
      - 'windows/**.h'
      - '**.sln'
      - '.github/**.yml'
      - 'scripts/**.ps1'

jobs:
  windows_build:
    runs-on: windows-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
      - name: Windows Build
        shell: pwsh
        id: windows_build_id
        run: |
          Get-ChildItem
