name: Windows Build
on:
  push:
    paths:
      - 'windows/**.cpp'
      - 'windows/**.h'
      - '**.sln'
      - '.github/**.yml'
      - 'scripts/**.ps1'
env:
  VS_PROGRAM: 1
  VS_FILE: 0
  VS_EPOCH:
  VS_FULL:
  RELEASE_TITLE: "RGB Diff"
  RELEASE_FILE: "./docs/md/pre-release.md"
  BIN_DEFAULT: "rgbdiff"
  PRERELEASE: True
  GH_TOKEN: ${{ github.token }}
jobs:
  windows_build:
    runs-on: windows-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
      - name: MSBuild Setup
        uses: microsoft/setup-msbuild@v2
      - name: Windows Build
        shell: pwsh
        id: windows_build_id
        run: |
          if (Test-Path -Path .\scripts\functions.ps1){
            . .\scripts\functions.ps1
            $br = BreakLine -Width 100 -Lines 2
          }
          $br; "Building application."; $br
          try {
            .\scripts\buildwindows.ps1
          } catch {
            $br; $_.Exception.Message; $br
          }
          $br; "Retrieving MD5 hash."; $br
          $epoch = [decimal] [datetimeoffset]::UtcNow.ToUnixTimeMilliseconds()
          "VS_FULL=${{ env.VS_PROGRAM }}.${{ env.VS_FILE }}.$epoch" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          "${{ env.VS_PROGRAM }}.${{ env.VS_FILE }}.$epoch" | Out-File -FilePath .\docs\latest_tag_name.txt
          $rgbdiff_x64_md5_text = @'
          {
            "schemaVersion": 1,
            "color": "2E9778",
            "label": "rgbdiff-x64.exe MD5",
            "message": "PLACEHOLDER",
            "labelColor": "1d1d1d",
            "style": "for-the-badge",
            "namedLogo": "windows"
          }
          '@
          Write-Output "$rgbdiff_x64_md5_text" > .\docs\json\rgbdiff_x64_md5.json
          $file = ".\docs\json\rgbdiff_x64_md5.json"
          $md5 = New-Object -TypeName System.Security.Cryptography.MD5CryptoServiceProvider
          $hash = $(Get-FileHash -Path "build\windows\rgbdiff.exe" -Algorithm MD5).Hash
          ((Get-Content -path $file -Raw) -replace 'PLACEHOLDER',$hash) | Set-Content -Path "$file"
          git add .\docs\json\* .\docs\latest_tag_name.txt
          git config --global user.name 'Lateralus138'
          git config --global user.email 'Lateralus138@users.noreply.github.com'
          git commit --allow-empty -am "Pushed .\docs\json\* to master. - $(Get-Date ([datetime]::UtcNow)) UTC"
          git push --force origin master
      - name: Release Windows
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          tag: ${{ env.VS_FULL }}
          name: ${{ env.RELEASE_TITLE }} - v${{ env.VS_FULL }}
          bodyFile: ${{ env.RELEASE_FILE }}
          prerelease: ${{ env.PRERELEASE }}
          artifacts: build\windows\${{ env.BIN_DEFAULT }}.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          
