name: Working Workflow

on:
  push:
    branches:
      - 'working'

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Working Test For Source File Changes
        shell: pwsh
        id: working_test_for_source_file_changes
        run: |
          $source_files_changed = (git diff --name-only HEAD^ HEAD | Where-Object { $_ -match '^.*\.(cpp|h|yml)$' }).Length -gt 0
          $readme_changed = (git diff --name-only HEAD^ HEAD | Where-Object { $_ -match '^.*\.(md)$' }).Length -gt 0
          Write-Host "name=source_files_changed::$source_files_changed" >> $Env:GITHUB_OUTPUT
          Write-Host "name=readme_changed::$readme_changed" >> $Env:GITHUB_OUTPUT
#Write-Host "::set-output name=files_changed::$source_files_changed"
#Write-Host "::set-output name=files_changed::$readme_changed"
      - name: Source Files Changed
        shell: pwsh
        if: steps.working_test_for_source_file_changes.outputs.source_files_changed == 'True'
        run: |
          "Source files changed."
      - name: README changed
        shell: pwsh
        if: steps.working_test_for_source_file_changes.outputs.readme_changed == 'True'
        run: |
          "README changed."
          