name: working linux build

on:
  workflow_run:
    workflows: [working windows build]
    types: [completed]
    branches: [working]

jobs:
  working_linux_build_test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Working Test For Source File Changes
        shell: bash
        id: working_test_for_source_file_changes
        run: |
          temp=($(find ./linux/src -type f -iname "*.cpp" -exec basename {} \; -o -iname "*.h" -exec basename {} \;))
          echo -e "Error:\t" $?
          temp+=($(find ./linux -maxdepth 1 -type f -iname "makefile" -exec basename {} \; -o -iname "prebuild" -exec basename {} \;))
          echo -e "Error:\t" $?
          temp+=($(find ./scripts -maxdepth 1 -type f -iname "*linux*.sh" -exec basename {} \;))
          echo -e "Error:\t" $?
          printf -v linux_source_files '%s|' ${temp[*]//\./\\\\.}
          echo -e "Error:\t" $?
          linux_source_files=${linux_source_files::-1}
          echo -e "Error:\t" $?
          eval echo hey
# linux_files=($(eval "git diff --name-only HEAD^ HEAD | grep -E '^.*($linux_source_files)$' --color=never"))
# echo -e "Error:\t" $? 
# linux_files_changed=false
# echo -e "Error:\t" $?
# if [[ ${#linux_files[@]} -gt 0 ]]; then
#   echo -e "Error:\t" $?  
#   linux_files_changed='True'
#   echo -e "Error:\t" $?
# fi
# echo -e "Error:\t" $?
# echo ${#linux_files[@]}
# echo -e "Error:\t" $?
# echo "linux_files_changed=$linux_files_changed" >> $GITHUB_OUTPUT
# echo -e "Error:\t" $?
      - name: Working Linux Build Test
        shell: bash
        if: steps.working_test_for_source_file_changes.outputs.windows_files_changed == 'True'
        run: |
          ./scripts/buildlinux.ps1
          if [[ $? -gt 0 ]]; then
            exit $?
          fi
          ls build/linux