name: Working Workflow

on:
  push:
    branches:
      - 'working'

jobs:
  working_build_test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Working Test For Source File Changes
        shell: pwsh
        id: working_test_for_source_file_changes
        run: |
          $windows_source_files =  (Get-ChildItem -Path .\windows\rgbdiff\ -File -Name | Where-Object { $_ -match '^.*\.(cpp|h)$' }) -join '|'
          $windows_source_files
          $windows_files = git diff --name-only HEAD^ HEAD | Where-Object { $_ -match "$('^(' + $windows_source_files + ')$')" }
          $windows_files
          $windows_files_changed = $windows_files.Length -gt 0
          $windows_files_changed
          Write-Output "windows_files_changed=$windows_files_changed" >> $Env:GITHUB_OUTPUT
      - name: MSBuild Setup
        uses: microsoft/setup-msbuild@v2
      - name: Working Windows Build Test
        shell: pwsh
        id: working_test_windows_build
        if: steps.working_test_for_source_file_changes.outputs.windows_files_changed == 'True'
        run: |
          .\scripts\buildwindows.ps1
          $LASTEXITCODE
          Get-ChildItem -Path .\build\windows\ -Recurse