name: working linux build

on:
  workflow_run:
    workflows: [working windows build]
    types: [completed]
    branches: [working]

jobs:
  working_linux_build_test:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Working
        uses: actions/checkout@v4
        with:
          ref: working
      - name: Working Test For Working Source File Changes
        shell: bash
        id: working_test_for_source_file_changes
        run: |
          declare -A linux_working_source_files
          for file in $(find ./linux/src -type f); do
            linux_working_source_files["$file"]="$(sha256sum "$file" | awk '{print $1}')"
          done
          linux_working_source_files_string="$(for key in "${!linux_working_source_files[@]}"; do echo "$key = ${linux_working_source_files[$key]}"; done)"
          linux_working_source_files_b64="$(echo "$linux_working_source_files_string" | base64 -w 0)"
          echo "linux_working_source_files_b64=$linux_working_source_files_b64" >> $GITHUB_OUTPUT
      - name: Checkout Master
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Working Test For Master Source File Changes
        shell: bash
        id: master_test_for_source_file_changes
        run: |
          function debug(){ echo "Here: $@"; }
          line=$(printf '%0.s-' {1..50})
          decode="${{ steps.working_test_for_source_file_changes.outputs.linux_working_source_files_b64 }}"
          readarray -d $'\n' -t linux_working_source_files_parse<<< "$(echo "$decode" | base64 -d)" 
          declare -A linux_master_source_files
          declare -A linux_working_source_files
          declare -a changed_files
          for arg in "${linux_working_source_files_parse[@]}"; do
            linux_working_source_files["$(echo "${arg}" | awk '{print $1}')"]="$(echo "${arg}" | awk '{print $3}')"
          done
          for file in $(find ./linux/src -type f); do
            linux_master_source_files["$file"]="$(sha256sum "$file" | awk '{print $1}')"
          done
          for key in "${!linux_working_source_files[@]}"; do
            if [[ "${linux_working_source_files[$key]}" != "${linux_master_source_files[$key]}" ]]; then
              changed_files+=("$key")
            fi
          done
          echo -e "${line}\n${line}"
          echo "changed_files=${#changed_files[@]}" >> $GITHUB_OUTPUT
      - name: Checkout Working
        uses: actions/checkout@v4
        with:
          ref: working
      - name: Working Build Test
        shell: bash
        id: working_build_test
        if: steps.master_test_for_source_file_changes.outputs.changed_files > 0
        run: |
          chmod +x ./scripts/buildlinux.sh
          chmod +x ./linux/prebuild
          ./scripts/buildlinux.sh
          chmod 0644 ./scripts/buildlinux.sh
          chmod 0644 ./linux/prebuild
          echo "successful_build=True" >> $GITHUB_OUTPUT
      - name: Commit files
        if: steps.working_build_test.outputs.successful_build == 'True'
        run: |
          git config --global user.name 'Lateralus138'
          git config --global user.email 'Lateralus138@users.noreply.github.com'
          git pull origin master --allow-unrelated-histories
          git checkout master
          git merge working
          git commit -a -m "Merged working to master."
          git push origin master
