name: working linux build

on:
  workflow_run:
    workflows: [working windows build]
    types: [completed]
    branches: [working]

jobs:
  working_linux_build_test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Working Test For Source File Changes
        shell: bash
        id: working_test_for_source_file_changes
        run: |
          GREP_COMMAND=('grep' '-E' '^.*(\.(yml|sh|cpp|h)|([mM][aA][kK][eE][fF][iI][lL][eE]|[pP][rR][eE][bB][uU][iI][lL][dD]))$' '--color=never')
          linux_files=($(git diff --name-only HEAD^ HEAD | "${GREP_COMMAND[@]}"))
          echo -e "Error 1:\t" $?
          linux_files_changed=false
          echo -e "Error:\t" $?
          if [[ ${#linux_files[@]} -gt 0 ]]; then
            echo -e "Error 2:\t" $?  
            linux_files_changed='True'
            echo -e "Error 3:\t" $?
          fi
          echo -e "Error 4:\t" $?
          echo ${#linux_files[@]}
          echo -e "Error 5:\t" $?
          echo "linux_files_changed=$linux_files_changed" >> $GITHUB_OUTPUT
          echo -e "Error 6:\t" $?
      - name: Working Linux Build Test
        shell: bash
        if: steps.working_test_for_source_file_changes.outputs.windows_files_changed == 'True'
        run: |
          ./scripts/buildlinux.ps1
          if [[ $? -gt 0 ]]; then
            exit $?
          fi
          ls build/linux