name: test flow

on:
  workflow_run:
    workflows: [working windows build]
    types: [completed]
    branches: [working]

jobs:
  working_linux_build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Working Test For Source File Changes
        shell: bash
        id: working_test_for_source_file_changes
        run: |
          linux_source_files=($(find ./linux/src -type f -iname "*.cpp" -exec basename {} \; -o -iname "*.h" -exec basename {} \;))
          linux_source_files+=($(find ./linux -maxdepth 1 -type f -iname "makefile" -exec basename {} \; -o -iname "prebuild" -exec basename {} \;))
          linux_source_files+=($(find ./scripts -maxdepth 1 -type f -iname "*linux*.sh" -exec basename {} \;))
          printf -v linux_source_files '%s|' ${linux_source_files[*]//\./\\\\.}
          linux_source_files=${linux_source_files::-1}
          linux_files=($(eval "git diff --name-only HEAD^ HEAD | grep -E '^.*($linux_source_files)$' --color=never"))
          linux_files_changed=false
          if [[ ${#linux_files[@]} -gt 0 ]]; then
            linux_files_changed='True' 
          fi
          echo "linux_files_changed=$linux_files_changed" >> $GITHUB_OUTPUT
      - name: Working Linux Build Test
        shell: bash
        if: steps.working_test_for_source_file_changes.outputs.windows_files_changed == 'True'
        run: |
          ./scripts/buildlinux.ps1
          if [[ $? -gt 0 ]]; then
            exit $?
          fi
          ls build/linux