name: working windows build

on:
  push:
    branches: [working]

jobs:
  working_windows_build_test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Working Test For Source File Changes
        shell: pwsh
        id: working_test_for_source_file_changes
        run: |
          $windows_source_files =  ((Get-ChildItem -Path .\windows\rgbdiff\ -File -Name | Where-Object { $_ -match '^.*\.(cpp|h)$' }) -join '|').Replace('.', '\.')
          $windows_source_files += '|.*\.ps1'
          $windows_files = git diff --name-only HEAD^ HEAD | Where-Object { $_ -match "$('^.*(' + $windows_source_files + ')$')" }
          $windows_files_changed = $windows_files.Length -gt 0
          Write-Output "windows_files_changed=$windows_files_changed" >> $Env:GITHUB_OUTPUT
      - name: MSBuild Setup
        uses: microsoft/setup-msbuild@v2
      - name: Working Windows Build Test
        shell: pwsh
        id: working_windows_test_build
        if: steps.working_test_for_source_file_changes.outputs.windows_files_changed == 'True'
        run: |
          .\scripts\buildwindows.ps1
          $windows_build_exists = $false
          if (Test-Path -Path ".\build\windows\rgbdiff.exe") { $windows_build_exists = $true }
          Write-Output "windows_build_exists=$windows_build_exists" >> $Env:GITHUB_OUTPUT
      - name: Working Windows Test For Merge
        shell: pwsh
        if: steps.working_windows_test_build.outputs.windows_build_exists == 'True'
        run: |
          git add .
          git diff --name-only