name: working linux build

on:
  workflow_run:
    workflows: [working windows build]
    types: [completed]
    branches: [working]

jobs:
  working_linux_build_test:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Working
        uses: actions/checkout@v4
        with:
          ref: working
      - name: Working Test For Working Source File Changes
        shell: bash
        id: working_test_for_working_source_file_changes
        run: |
          declare -A linux_working_source_files
          for file in $(find ./linux/src -type f); do
            linux_working_source_files["$file"]="$(sha256sum "$file" | awk '{print $1}')"
          done
          linux_working_source_files_string="$(for key in "${!linux_working_source_files[@]}"; do echo "$key = ${linux_working_source_files[$key]}"; done)"
          linux_working_source_files_b64="$(echo "$linux_working_source_files_string" | base64 -w 0)"
          echo "linux_working_source_files_b64=$linux_working_source_files_b64" >> $GITHUB_OUTPUT
      - name: Checkout Master
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Working Test For Master Source File Changes
        shell: bash
        id: working_test_for_master_source_file_changes
        run: |
          function debug(){ echo "Here: $@"; }
          debug 1
          line=$(printf '%0.s-' {1..50})
          debug 2
          IFS=$'\n' read -rd '' -a linux_working_source_files <<<"$(echo "${{ steps.working_test_for_working_source_file_changes.outputs.linux_working_source_files_b64 }}" | base64 -d)"
          debug 3
          declare -A linux_master_source_files
          debug 4
          for file in $(find ./linux/src -type f); do
            linux_master_source_files["$file"]="$(sha256sum "$file" | awk '{print $1}')"
          done
          debug 5
          for key in "${!linux_working_source_files[@]}"; do
            echo -e "${line}\nWorking\n${line}"
            echo "$key = ${linux_working_source_files[$key]}"
            echo -e "${line}\nMaster\n${line}"
            echo "$key = ${linux_master_source_files[$key]}"
            echo -e "${line}"
          done
          debug 6
          echo -e "${line}\n${line}"
          debug 7