name: working linux build

on:
  workflow_run:
    workflows: [working windows build]
    types: [completed]
    branches: [working]

jobs:
  working_linux_build_test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Working Test For Source File Changes
        shell: bash
        id: working_test_for_source_file_changes
        run: |
          GREP_COMMAND=('grep' '-E' '^.*(\.(yml|sh|cpp|h)|([mM][aA][kK][eE][fF][iI][lL][eE]|[pP][rR][eE][bB][uU][iI][lL][dD]))$' '--color=never')
          linux_files=($(git diff --name-only HEAD^ HEAD | "${GREP_COMMAND[@]}"))
          linux_files_changed=false
          if [[ ${#linux_files[@]} -gt 0 ]]; then
            linux_files_changed=true
          fi
          echo "linux_files_changed=$linux_files_changed" >> $GITHUB_OUTPUT
      - name: Working Linux Build Test
        shell: bash
        id: working_test_build
        if: steps.working_test_for_source_file_changes.outputs.linux_files_changed == 'True'
        run: |
          chmod +x ./scripts/buildlinux.sh
          chmod +x ./linux/prebuild
          ./scripts/buildlinux.sh
          linux_build_exists=false
          if [[ -e "./build/linux/rgbdiff" ]]; then
            linux_build_exists=true
          fi
          echo "linux_build_exists=$linux_build_exists" >> $GITHUB_OUTPUT
      - name: Working Linux Test For Merge
        shell: bash
        if: steps.working_test_build.outputs.linux_build_exists == 'True'
        run: |
          echo "Ready for merge."